// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.5.0
// source: policy.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PolicyService_ContainerPolicy_FullMethodName = "/policy.PolicyService/containerPolicy"
	PolicyService_HostPolicy_FullMethodName      = "/policy.PolicyService/hostPolicy"
	PolicyService_GetHostPolicy_FullMethodName   = "/policy.PolicyService/getHostPolicy"
	PolicyService_BaselineScan_FullMethodName    = "/policy.PolicyService/baselineScan"
	PolicyService_BaselineRepair_FullMethodName  = "/policy.PolicyService/baselineRepair"
	PolicyService_BaselineBack_FullMethodName    = "/policy.PolicyService/baselineBack"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	ContainerPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error)
	HostPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error)
	GetHostPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	BaselineScan(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error)
	BaselineRepair(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error)
	BaselineBack(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) ContainerPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PolicyService_ContainerPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) HostPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PolicyService_HostPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) GetHostPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, PolicyService_GetHostPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) BaselineScan(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error) {
	out := new(BaselineResponse)
	err := c.cc.Invoke(ctx, PolicyService_BaselineScan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) BaselineRepair(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error) {
	out := new(BaselineResponse)
	err := c.cc.Invoke(ctx, PolicyService_BaselineRepair_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) BaselineBack(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*BaselineResponse, error) {
	out := new(BaselineResponse)
	err := c.cc.Invoke(ctx, PolicyService_BaselineBack_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations should embed UnimplementedPolicyServiceServer
// for forward compatibility
type PolicyServiceServer interface {
	ContainerPolicy(context.Context, *Policy) (*Response, error)
	HostPolicy(context.Context, *Policy) (*Response, error)
	GetHostPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error)
	BaselineScan(context.Context, *Policy) (*BaselineResponse, error)
	BaselineRepair(context.Context, *Policy) (*BaselineResponse, error)
	BaselineBack(context.Context, *Policy) (*BaselineResponse, error)
}

// UnimplementedPolicyServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPolicyServiceServer struct {
}

func (UnimplementedPolicyServiceServer) ContainerPolicy(context.Context, *Policy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) HostPolicy(context.Context, *Policy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) GetHostPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) BaselineScan(context.Context, *Policy) (*BaselineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaselineScan not implemented")
}
func (UnimplementedPolicyServiceServer) BaselineRepair(context.Context, *Policy) (*BaselineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaselineRepair not implemented")
}
func (UnimplementedPolicyServiceServer) BaselineBack(context.Context, *Policy) (*BaselineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaselineBack not implemented")
}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_ContainerPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ContainerPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ContainerPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ContainerPolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_HostPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).HostPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_HostPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).HostPolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_GetHostPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetHostPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetHostPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetHostPolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_BaselineScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).BaselineScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_BaselineScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).BaselineScan(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_BaselineRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).BaselineRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_BaselineRepair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).BaselineRepair(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_BaselineBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).BaselineBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_BaselineBack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).BaselineBack(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "containerPolicy",
			Handler:    _PolicyService_ContainerPolicy_Handler,
		},
		{
			MethodName: "hostPolicy",
			Handler:    _PolicyService_HostPolicy_Handler,
		},
		{
			MethodName: "getHostPolicy",
			Handler:    _PolicyService_GetHostPolicy_Handler,
		},
		{
			MethodName: "baselineScan",
			Handler:    _PolicyService_BaselineScan_Handler,
		},
		{
			MethodName: "baselineRepair",
			Handler:    _PolicyService_BaselineRepair_Handler,
		},
		{
			MethodName: "baselineBack",
			Handler:    _PolicyService_BaselineBack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy.proto",
}
